build:
  image: maven:3.6.3-openjdk-11
  stage: build
  script:
    - mvn clean package
    - mkdir ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -t rsa idemidov.ru >> ~/.ssh/known_hosts
    - scp target/code-editor-gateway.jar admin@idemidov.ru:/home/admin/Projects/web-ide-project
  artifacts:
    expire_in: 10 days
    paths:
      - target
