build:
  image: maven:3.6.3-openjdk-11
  stage: build
  script:
    - mvn clean package
    - mkdir ~/.ssh
    - chmod 700 ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - ssh-keyscan -t rsa idemidov.ru >> ~/.ssh/known_hosts
    - scp target/code-editor-gateway.jar admin@idemidov.ru:/home/admin/Projects/web-ide-project/gateway.jar
    - ssh admin@idemidov.ru "echo $ACCEPT_KEY | sudo -S docker restart java-gateway"
  artifacts:
    expire_in: 10 days
    paths:
      - target
