build:
  image: maven:3.6.3-openjdk-11-slim
  stage: build
  script:
    - apt-get install openssh-client -y
    - mvn clean package
    - scp target/code-editor-gateway.jar admin@idemidov.ru:/home/admin/Projects/web-ide-project
  artifacts:
    expire_in: 10 days
    paths:
      - target
